### ISSUE TITLE
数据没办法正常下载下来

### ISSUE THREAD

**Issue by zhtpro723** [ShichenXie/pedquant#10]
> datt <- md_stock(symbol = '000002.sz',
+                  from = "2002-01-01",
+                  to = "2019-12-31", source = "163")
1/1 000002.sz
Warning message:                                                                                                                                 
One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat)

**Comment by ShichenXie** [comment]
数据源关服务了，回头我看看有没有可替换的数据源

**Comment by zhtpro723** [comment]
> 数据源关服务了，回头我看看有没有可替换的数据源

请问有解决的办法了吗

**Comment by ShichenXie** [comment]
这个函数的问题解决了，可以升级试试看看，`devtools::install_github("shichenxie/pedquant")`

**Comment by roywwei** [comment]
感谢大佬

**Comment by Tia1892** [comment]
更新后还是不行。结果显示：
[1] "Error in setnames(rbindlist(datlst), c(\"date\", \"open\", \"close\", \"high\",  : \n  Can't assign 14 names to a 0 column data.table\n"
attr(,"condition")
<simpleError in setnames(rbindlist(datlst), c("date", "open", "close", "high",     "low", "volume", "amount", "amplitude", "change_pct", "change",     "turnover", "symbol", "name", "market")): Can't assign 14 names to a 0 column data.table>

**Comment by ShichenXie** [comment]
给个报错的例子

**Comment by hallo128** [comment]
> devtools::install_github("shichenxie/pedquant")
> library(pedquant)
> d1=md_stock('300957',from='2021-04-01',to='2022-07-01')

仍然报错：
1/1 300957
Warning message:                                                      
One or more parsing issues, call `problems()` on your data frame for
details, e.g.:
  dat <- vroom(...)
  problems(dat)

**Comment by ShichenXie** [comment]
> > devtools::install_github("shichenxie/pedquant")
> > library(pedquant)
> > d1=md_stock('300957',from='2021-04-01',to='2022-07-01')

再试试看

**Comment by hallo128** [comment]
> 

可以了，感谢作者。现在可以正常下载了
