### ISSUE TITLE
ed_nbs error: the condition has length > 1

### ISSUE THREAD

**Issue by l2dy** [ShichenXie/pedquant#11]
The following code throws an error, but with `eng = TRUE`, it runs successfully.

```
> ed_nbs(
+   symbol = "A010804",
+   freq = "monthly",
+   geo_type = "city",
+   subregion = "all",
+   from = ymd("2006-01-01"),
+   to = ymd("2022-12-31")
+ )
Error in if (dat2[, unique(nchar(date))] == 6) { : 
  the condition has length > 1
```

pedquant version: 0.2.1 from CRAN

**Comment by ShichenXie** [comment]
修复了，你安装github上面的版本试试看

**Comment by l2dy** [comment]
The GitHub version throws another error.

```
Error in match.arg(unit, c("ms", "s", "d")) :
  'arg' should be one of “ms”, “s”, “d”
```

https://github.com/ShichenXie/pedquant/blob/209f3bfa075cc7de49acabac4e3d28d56227fea5/R/ed_nbs.R#L146

environment:
R version 4.2.3
xefun version 0.1.3

**Comment by l2dy** [comment]
It worked with both pedquant and xefun installed from GitHub. Thanks!

**Comment by ShichenXie** [comment]
OK, I have upload the latest version  xefun to CRAN.
