### ISSUE TITLE
复权后股价与其他公共数据不一致

### ISSUE THREAD

**Issue by flystar233** [ShichenXie/pedquant#12]
pedquant:
![image](https://user-images.githubusercontent.com/20431495/231041427-6c64a3ff-ca44-4e28-94e4-b6b0e161d80c.png)
google:
![image](https://user-images.githubusercontent.com/20431495/231041578-04794e78-175b-4331-92e5-af5fa0716dfc.png)

**Comment by ShichenXie** [comment]
`tsla = md_stock('TSLA', forward = FALSE)`
forward设为FALSE，即后复权价格，与google展示的是一致的
