### ISSUE TITLE
 pq_plot(rbindlist(dt_nbs)[, symbol := symbol[.N]] 报错

### ISSUE THREAD

**Issue by Luke-LH** [ShichenXie/pedquant#14]
http://shichen.name/slide/20190525pedquant/#13

# line chart
p1 = pq_plot(rbindlist(dt_nbs)[, symbol := symbol[.N]], 
    from = '2000-1-1', chart_type = 'step')

运行结果如下：
Error in get(y)[.N] : object of type 'closure' is not subsettable

不知何故？

**Comment by ShichenXie** [comment]
pq_plot 函数更新了，需要指定 y 坐标的变量名
`p1 = pq_plot(rbindlist(dt_nbs)[, symbol := ‘cpi’], y='value', chart_type = 'step')`

**Comment by Luke-LH** [comment]
谢谢！后来我也试着增加x轴和y轴，挺好用，还在课上推荐给了学生。期待越来越好！
