### ISSUE TITLE
谢老师，蜡烛图为啥画不了啊

### ISSUE THREAD

**Issue by hxx2001** [ShichenXie/pedquant#15]
<img width="891" alt="88c1cd75d599d2e448b5d80c743dc1c" src="https://github.com/ShichenXie/pedquant/assets/124670831/9c1a13fc-5b4c-4c83-919d-16c4dfdead02">

**Comment by ShichenXie** [comment]
重启R试试呢

**Comment by hxx2001** [comment]
老师你好，好像还是不行，是不是我pq_plot里面参数选的不对啊，因为我看您那个网站没有画蜡烛图的示例，所以是不是参数我自己设置的不对

**Comment by ShichenXie** [comment]
更新到GitHub上面的最新版试试

**Comment by hxx2001** [comment]
好的成功了，谢谢老师
