### ISSUE TITLE
查询股票数据，股票代码会重合吗

### ISSUE THREAD

**Issue by hxx2001** [ShichenXie/pedquant#17]
谢老师，请教一个问题，查询国外股票数据时，pedquant好像只接收不加后缀的，如CMS，而不能接收CMS.N这种加了证券交易所标识符的，那要是存在xxx股票代码在两个不同的证券交易所，那会撞吗

**Comment by ShichenXie** [comment]
目前好像也就支持美股和港股吧，这两个好像没有重复的
