### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by tulipsliu** [ShichenXie/pedquant#2]
dear author,

i download the package,but i don`t known how to use this package .

can give me a pdf file 

yours daniel tulips liu

email : xudongliu520@vip.qq.com

**Comment by ShichenXie** [comment]
你看看 www.pedquant.com 这个网站。总共也没几个函数

**Comment by tulipsliu** [comment]
谢谢。&nbsp;

 Yours
Danniel Tulips Liu


Shanghai,China.


&nbsp;

**Comment by tulipsliu** [comment]
你好，我也想开发一个工具包试一试，我会MATLAB编程基础还可以。现在也用 rstudio&nbsp; 可以给我一些检验不。在国内没，我的qq&nbsp; 280201722&nbsp;

 Yours
Daniel Tulips Liu


BeiJing,China.


&nbsp;

**Comment by ShichenXie** [comment]
你的回复一会儿是北京一会儿是上海。为啥中间还有乱符。奇怪。
