### ISSUE TITLE
ed_nbs(...) gives "The data from NBS is not available" every time

### ISSUE THREAD

**Issue by oziozdoba** [ShichenXie/pedquant#3]
Hi, I tried to run my scripts with NBS data, I haven't checked them since half a year, but unfortunately it stoped working. Every time i try to get the data, I get: 

> Błąd w poleceniu 'nbs_symbol1(geo_type, freq, sel_symbol, eng)':
>   The data from NBS is not available.

I get this error with my parts of code:

> A020101 <- ed_nbs(geo_type='n', freq='y', symbol='A020101', date_range='max', eng = TRUE)

as well as with  examples from Your reference manual in pdf.

Is there any chance it will get fixed or is it NBS servers fault? 
Thank You :)

**Comment by ShichenXie** [comment]
http://data.stats.gov.cn/

The NBS database website is under upgrading. Please wait and try again later.

**Comment by oziozdoba** [comment]
Thanks for the reply. I checked a day before adding the issue and website was still working, Now I see the notification, hope they don't introduce major systematical changes to the database ;)

**Comment by ShichenXie** [comment]
I have fixed the bug (533a7cdb90a9cb8acc53a43eb73854cba923d7af). Please install the latest version from github via `devtools::install_github("shichenxie/pedquant")` and try your codes again.

**Comment by oziozdoba** [comment]
Thanks, works fine 👍 :)
