### ISSUE TITLE
希望增加股票股息率和配股相关函数

### ISSUE THREAD

**Issue by MelonPP** [ShichenXie/pedquant#4]
谢博士，谢谢您提供这么给力的package，在国内使用非常方便。
不过这个目前好像还不支持提取股息以及拆股配股相关数据，请问可否在后续开发中拓展一下相关功能？

**Comment by ShichenXie** [comment]
有这个功能的
```
library(pedquant)

datadj1 = md_stock('000001', type=c('adjfactor'), source = 'yahoo')
datadj2 = md_stock('000001', type=c('adjfactor'), source = '163')
```

**Comment by MelonPP** [comment]
> 有这个功能的
> 
> ```
> library(pedquant)
> 
> datadj1 = md_stock('000001', type=c('adjfactor'), source = 'yahoo')
> datadj2 = md_stock('000001', type=c('adjfactor'), source = '163')
> ```

哦，好的，谢谢~
