### ISSUE TITLE
网易数据源，md_stock函数下载北交所股票日线数据出错。

### ISSUE THREAD

**Issue by zhangyibin1976** [ShichenXie/pedquant#7]
> md_stock("831726")
1/1 831726
$`831726`
[1] "Error in setnames(rbindlist(datlst), c(\"date\", \"open\", \"close\", \"high\",  : \n  无法指定 14 命名 0 data.table 的纵列\n"
attr(,"condition")
<simpleError in setnames(rbindlist(datlst), c("date", "open", "close", "high",     "low", "volume", "amount", "amplitude", "change_pct", "change",     "turnover", "symbol", "name", "market")): 无法指定 14 命名 0 data.table 的纵列>

**Comment by ShichenXie** [comment]
嗯，网易不提供北交所的数据
